repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.101.1
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive
      - id: terraform_validate
      - id: terraform_docs
        args:
          - --args=--lockfile=false
      - id: terraform_tflint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict # Проверка на оставшиеся маркеры слияния
      - id: end-of-file-fixer    # Убеждается, что файл заканчивается новой строкой
      - id: trailing-whitespace  # Удаляет лишние пробелы в конце строк
